<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\avcodec-62.dll">
      <Private>True</Private>
    </Reference>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\avdevice-62.dll">
      <Private>True</Private>
    </Reference>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\avfilter-11.dll">
      <Private>True</Private>
    </Reference>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\avformat-62.dll">
      <Private>True</Private>
    </Reference>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\avutil-60.dll">
      <Private>True</Private>
    </Reference>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\swresample-6.dll">
      <Private>True</Private>
    </Reference>
    <Reference Include="..\ffmpeg-8.0.1-full_build-shared\bin\swscale-9.dll">
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
